name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone --depth=1 "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" .
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt pytest
      - name: Run tests
        run: python3 -m pytest -q
      - name: Compile Python sources
        run: python3 -m compileall -q app
